---
- name: create ceph directory
  file:
    path: /etc/ceph
    state: directory

- name: create client.cinder.key
  shell: ceph auth get-key client.cinder > /etc/ceph/client.cinder.key
         creates=/etc/ceph/client.cinder.key
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"

- name: fetch client.cinder.key
  slurp: path=/etc/ceph/client.cinder.key
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: client_cinder_key

- name: write client.cinder.key
  copy:
    dest: /etc/ceph/client.cinder.key
    content: "{{ client_cinder_key['content'] | b64decode }}"
    mode: 0600

# used in secret.xml
- name: fetch contents of uuid file
  slurp: path=/etc/ceph/cinder_uuid
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: cinder_uuid_file

- name: generate ceph secret xml file
  template:
    src: etc/ceph/secret.xml
    dest: /etc/ceph/secret.xml
    owner: root
    group: root
    mode: 0600

- name: define virsh secret
  shell: virsh secret-define --file /etc/ceph/secret.xml

- name: set virsh secret
  shell: "virsh secret-set-value --secret {{ cinder_uuid_file.content | b64decode }} --base64 $(cat /etc/ceph/client.cinder.key)"

# for nova user in ceph
- name: create client.nova.key
  shell: ceph auth get-key client.nova > /etc/ceph/client.nova.key
         creates=/etc/ceph/client.nova.key
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  when: nova.backend_ceph|bool


- name: fetch client.nova.key
  slurp: path=/etc/ceph/client.nova.key
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: client_nova_key
  when: nova.backend_ceph|bool
  
- name: write client.nova.key
  copy:
    dest: /etc/ceph/client.nova.key
    content: "{{ client_nova_key['content'] | b64decode }}"
  when: nova.backend_ceph|bool
  
- name: fetch contents of nova_uuid file
  slurp: path=/etc/ceph/nova_uuid
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: nova_uuid_file
  when: nova.backend_ceph|bool

- name: generate ceph secret-nova xml file
  template: src=etc/ceph/secret-nova.xml
            dest=/etc/ceph/secret-nova.xml
            owner=root
            group=root
            mode=0644
  when: nova.backend_ceph|bool

- name: define virsh secret for nova
  shell: virsh secret-define --file /etc/ceph/secret-nova.xml
  when: nova.backend_ceph|bool

- name: set virsh secret for nova
  shell: "virsh secret-set-value --secret {{ nova_uuid_file.content | b64decode }} --base64 $(cat /etc/ceph/client.nova.key)"
  when: nova.backend_ceph|bool
