---
- name: install ceilometer polling agent
  upstart_service: name=ceilometer-polling
                   user=ceilometer
                   cmd=/usr/local/bin/ceilometer-polling
  notify: restart ceilometer services

- name: install libvirt-python in package venv
  command: "{{ 'ceilometer'|ursula_package_path(openstack_package_version) }}/bin/pip install libvirt-python"
  notify: restart ceilometer services
  when: openstack_install_method == 'package'

- name: install libvirt-python in source venv
  command: "{{ openstack_source.virtualenv_base }}/ceilometer/bin/pip install libvirt-python"
  notify: restart ceilometer services
  when: openstack_install_method == 'source'

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart ceilometer services
  when: code_has_changed | default('False') | bool and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: start ceilometer-polling service
  service:
    name: ceilometer-polling
    state: started

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool
