---
- name: test for presence of local keypair
  stat: path={{ testenv_keypair_path }}
  register: testenv_keypair_local

- name: delete remote keypair
  nova_keypair: name={{ testenv_keypair_name }} state=absent
  when: not testenv_keypair_local.stat.exists

- name: create the keypair
  nova_keypair: name={{ testenv_keypair_name }} state=present
  register: testenv_keypair

- name: persist the keypair
  copy:
    dest: "{{ testenv_keypair_path }}"
    content: "{{ testenv_keypair.key }}"
    mode: 0600
  when: testenv_keypair.changed
