---
- name: fetch rados.py
  get_url: url=https://raw.githubusercontent.com/ceph/ceph/{{ ceph.ceph_version }}/src/pybind/rados.py
           dest="{{ openstack_source.virtualenv_base }}/cinder/lib/python2.7/site-packages/rados.py"
           owner=root
           group=root
           mode=0644
  when: openstack_install_method == 'source'

- name: fetch rbd.py
  get_url: url=https://raw.githubusercontent.com/ceph/ceph/{{ ceph.ceph_version }}/src/pybind/rbd.py
           dest="{{ openstack_source.virtualenv_base }}/cinder/lib/python2.7/site-packages/rbd.py"
           owner=root
           group=root
           mode=0644
  when: openstack_install_method == 'source'

- name: fetch rados.py
  get_url: url=https://raw.githubusercontent.com/ceph/ceph/{{ ceph.ceph_version }}/src/pybind/rados.py
           dest="{{ lookup('items', 'openstack_package.virtualenv_base') }}/cinder/lib/python2.7/site-packages/rados.py"
           owner=root
           group=root
           mode=0644
  when: openstack_install_method == 'package'

- name: fetch rbd.py
  get_url: url=https://raw.githubusercontent.com/ceph/ceph/{{ ceph.ceph_version }}/src/pybind/rbd.py
           dest="{{ lookup('items', 'openstack_package.virtualenv_base') }}/cinder/lib/python2.7/site-packages/rbd.py"
           owner=root
           group=root
           mode=0644
  when: openstack_install_method == 'package'

- name: fetch cinder keyring
  slurp: path=/etc/ceph/ceph.client.cinder.keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: cinder_keyring

- name: write cinder keyring
  copy:
    dest: "{{ cinder_keyring['source'] }}"
    content: "{{ cinder_keyring['content'] | b64decode }}"
    mode: 0644
    owner: cinder
    group: cinder

# used in cinder.conf
- name: fetch contents of uuid file
  slurp: path=/etc/ceph/cinder_uuid
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: cinder_uuid_file
