---
- name: check if cinder user exists
  shell: getent passwd cinder
  register: cinder_user
  failed_when: False
  changed_when: False

- name: cinder user
  user: name=cinder shell=/bin/false createhome=no
  when: cinder_user|success

- name: cinder user
  user: name=cinder comment=cinder shell=/bin/false system=yes
        home=/nonexistent createhome=no
  when: not cinder_user|success

- name: /etc/cinder
  file: dest=/etc/cinder state=directory

- name: cinder image dir (and leading paths)
  file: dest={{ cinder.state_path }}/images state=directory owner=cinder group=cinder

- name: cinder private dirs
  file:
    dest: "{{ item }}"
    state: directory
    mode: 0700
    owner: cinder
    group: cinder
  with_items:
    - /var/cache/cinder
    - "{{ cinder.state_path }}/lock"

- name: cinder log dir
  file: dest=/var/log/cinder state=directory mode=2750 owner=cinder group=adm

- name: Change cinder log dir acl
  acl: name=/var/log/cinder state=present default=yes etype={{ item.etype }} permissions={{ item.permission }}
  with_items:
    - etype: user
      permission: rw
    - etype: group
      permission: r
    - etype: other
      permission: r

# needs to happen before 'cinder config'
- include: ceph_integration.yml
  when: ceph.enabled|bool

- name: error out when swift haproxy vip is not updated
  fail: msg="swift haproxy vip needs to be updated for use with cinder backup"
  when: swift.enabled|bool and (endpoints.swift.haproxy_vip == fqdn)

- name: cinder config
  template: src={{ item }} dest=/etc/cinder mode={{ 0644 if 'policy.json' in item else 0640 }}
            owner=cinder group=cinder
  with_fileglob: ../templates/etc/cinder/*
  notify:
    - restart cinder services
    - restart cinder backup service

- name: cinder sudoer
  template: src=etc/sudoers.d/cinder dest=/etc/sudoers.d/cinder owner=root
            group=root mode=0440

- include: logging.yml
  tags:
    - logrotate
    - logging

- include: serverspec.yml
  tags: 
    - serverspec
  when: serverspec.enabled|default('False')|bool

