---
project_name: aodh
aodh:
  debug: False
  source:
    rev: 'stable/mitaka'
    constrain: True
    upper_constraints: 'https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt'
    python_dependencies:
      - { name: PyMySQL }
      - { name: python-memcached }
      - { name: python-ceilometerclient }
    system_dependencies: []
  alternatives:
    - aodh-evaluator
    - aodh-notifier
    - aodh-listener
    - aodh-expirer
    - aodh-api
    - aodh-dbsync
  logs:
    - paths:
      - /var/log/aodh/aodh-api.log
      fields:
        type: openstack
        tags: aodh,aodh-api
    - paths:
      - /var/log/aodh/aodh-listener.log
      fields:
        type: openstack
        tags: aodh,aodh-listener
    - paths:
      - /var/log/aodh/aodh-notifier.log
      fields:
        type: openstack
        tags: aodh,aodh-notifier
    - paths:
      - /var/log/aodh/aodh-expirer.log
      fields:
        type: openstack
        tags: aodh,aodh-expirer
    - paths:
      - /var/log/aodh/aodh-evaluator.log
      fields:
        type: openstack
        tags: aodh,aodh-evaluator
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
