---
- name: heat-api process check
  sensu_process_check: service=heat-api
  notify: restart sensu-client

- name: heat-api-cfn process check
  sensu_process_check: service=heat-api-cfn
  notify: restart sensu-client

- name: heat-engine process check
  sensu_process_check: service=heat-engine
  notify: restart sensu-client

- name: heat-api check
  sensu_check: name=check-heat-api plugin=check-os-api.rb
               args="--service heat --criticality {{ heat.monitoring.sensu_checks.check_heat_api.criticality }}"
  notify: restart sensu-client

- name: heat sla metrics
  sensu_metrics_check: name=heat-sla-metrics plugin=metrics-os-api.py
                       args='-S heat --scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client
