---
- name: swift-account service scripts
  upstart_service: name=swift-{{ item.name }} 
                   cmd=/usr/local/bin/swift-{{ item.cmd|default(item.name) }}
                   args=/etc/swift/account-server.conf
                   user=swift
  with_items:
    - { name: account, cmd: account-server }
    - { name: account-auditor }
    - { name: account-reaper }
    - { name: account-replicator }

- stat: path=/etc/swift/account.ring.gz
  register: account_ring

- set_fact: start_account={{ account_ring.stat.exists }}

- name: account-server config
  template: src=etc/swift/account-server.conf mode=0640
            dest=/etc/swift/account-server.conf owner=swift group=swift
  notify:
    - restart swift-account-services

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart swift-account-services
  when: code_has_changed | default('False') | bool and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: start swift-account services
  service: name={{ item }} state=started
  with_items:
    - swift-account-replicator
    - swift-account-auditor
    - swift-account-reaper
    - swift-account
  when: start_account|bool
