---
- name: install cinder-data required packages
  apt: pkg={{ item }}
  with_items:
    - cryptsetup
    - lvm2
    - tgt
    - nbd-client
    - open-iscsi
    - qemu-utils
  register: result
  until: result|succeeded
  retries: 5

- name: iscsi target framework conf dir
  file: dest=/etc/tgt/conf.d state=directory

- name: tgt config files
  template: src={{ item.value.src }} dest={{ item.value.dest }} mode=0644
  with_dict:
    targets:
      src: etc/tgt/targets.conf
      dest: /etc/tgt/targets.conf
    cinder_tgt:
      src: etc/tgt/conf.d/cinder_tgt.conf
      dest: /etc/tgt/conf.d/cinder_tgt.conf

- name: ensure tgt service is running
  service: name=tgt state=started

- include: volume_group.yml
  when: cinder.create_vg|bool and ( cinder.fixed_key is not defined or (cinder.fixed_key is defined and "compute" not in group_names) )

- name: iscsi start
  service: name=open-iscsi state=started

- name: enable cinder encryption
  template: src=etc/cinder/cinder.encryption.conf dest=/etc/cinder/cinder.encryption.conf mode=0640
            owner=root group=cinder
  notify: restart cinder services
  when: cinder.fixed_key is defined

- name: disable cinder encryption
  file: dest=/etc/cinder/cinder.encryption.conf state=absent
  notify: restart cinder services
  when: cinder.fixed_key is not defined

- name: install cinder-volume service
  upstart_service: name=cinder-volume user=cinder
                   cmd=/usr/local/bin/cinder-volume
                   config_dirs=/etc/cinder

- name: install cinder backup service
  upstart_service: name=cinder-backup
                   user=cinder
                   cmd=/usr/local/bin/cinder-backup
                   config_dirs=/etc/cinder
  when: swift.enabled|default("false")|bool

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify:
    - restart cinder services
    - restart cinder backup service
  when: code_has_changed | default('False') | bool and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: start cinder-volume
  service:
    name: cinder-volume
    state: started
  delegate_to: "{{ item }}"
  run_once: True
  with_items: "{{ play_hosts }}"

- name: start cinder backup
  service:
    name: cinder-backup
    state: started
  delegate_to: "{{ item }}"
  run_once: True
  when: swift.enabled|default("false")|bool
  with_items: "{{ play_hosts }}"

- include: monitoring.yml
  when: monitoring.enabled|default('True')|bool
  tags:
    - monitoring
    - common
