---
# cinder volume
- name: cinder-volume process check
  sensu_process_check: service=cinder-volume
  notify: restart sensu-client

- name: iscsid process check
  sensu_process_check: service=iscsid
  notify: restart sensu-client
  when: "'rbd_volumes' not in cinder.enabled_backends"

- name: cinder volume group metrics
  sensu_metrics_check: name=cinder-vg-metrics plugin=metrics-volgroup.sh
                       args='-v cinder-volumes -s {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client
  when: cinder.create_vg|bool and ( cinder.fixed_key is not defined or (cinder.fixed_key is defined and "compute" not in group_names) )

- name: cinder-backup process check
  sensu_process_check: service=cinder-backup
  notify: restart sensu-client
  when: swift.enabled|default("False")|bool
