---
- name: restart swift-account-services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - swift-account
    - swift-account-auditor
    - swift-account-reaper
    - swift-account-replicator
  when: start_account|bool
