---
- name: swift-container service scripts
  upstart_service: name=swift-{{ item.name }}
                   cmd=/usr/local/bin/swift-{{ item.cmd|default(item.name) }}
                   args=/etc/swift/container-server.conf
                   user=swift
  with_items:
    - { name: container, cmd: container-server }
    - { name: container-auditor }
    - { name: container-replicator }
    - { name: container-sync }
    - { name: container-updater }

- stat: path=/etc/swift/container.ring.gz
  register: container_ring

- set_fact: start_container={{ container_ring.stat.exists }}

- name: container-server config
  template: src=etc/swift/container-server.conf mode=0640
            dest=/etc/swift/container-server.conf owner=swift group=swift
  notify: 
    - restart-swift-container-services

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart-swift-container-services
  when: code_has_changed | default('False') | bool and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: start swift-container services
  service: name={{ item }} state=started
  with_items:
    - swift-container
    - swift-container-auditor
    - swift-container-replicator
    - swift-container-sync
    - swift-container-updater
  when: start_container|bool
