---
- name: restart swift-proxy service
  service: name=swift-proxy state=restarted

- name: restart haproxy
  service: name=haproxy state=restarted

- name: restart memcached
  action: service name=memcached state=restarted enabled=yes
