---
- name: neutron agents check
  sensu_check_dict:
    name: "check-neutron-agents"
    check: "{{ sensu_checks.neutron.check_neutron_agents }}"
  notify: restart sensu-client missing ok

- name: neutron agents duplicate check
  sensu_check_dict:
    name: "check-neutron-agents-duplicate"
    check: "{{ sensu_checks.neutron.check_neutron_agents_duplicate }}"
  notify: restart sensu-client missing ok
