---
magnum:
  port: 9512
  host: 127.0.0.1
  heartbeat_timeout_threshold: 30
  source:
    rev: 'stable/mitaka'
    constrain: True
    upper_constraints: 'https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt'
    virtualenv: "/opt/openstack/magnum"
    python_dependencies:
      - { name: PyMySQL }
    system_dependencies: []
  package: ~
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
  logs:
    - paths:
      - /var/log/magnum/magnum-api.log
      fields:
        type: openstack
        tags: magnum,api,api
    - paths:
      - /var/log/magnum/magnum-conductor.log
      fields:
        type: openstack
        tags: magnum,conductor
  logging:
    debug: False
    verbose: True
  alternatives:
    - magnum-api
    - magnum-conductor
    - magnum-db-manage
    - magnum-template-manage
