---
- name: install mod_auth_openidc deps
  apt: name={{ item }} state=present
  with_items:
    - libjansson4
    - libhiredis0.10
    - libcurl3
  register: result
  until: result|succeeded
  retries: 5

- name: download mod_auth_openidc
  get_url: url={{ keystone.federation.sp.oidc.download.url }}
           dest=/tmp/{{ keystone.federation.sp.oidc.module_name }}

- name: install mod_auth_openidc
  apt: deb=/tmp/{{ keystone.federation.sp.oidc.module_name }}
       install_recommends=yes
  notify: reload apache
  register: result
  until: result|succeeded
  retries: 5

- name: enable apache mod auth_openidc
  apache2_module: name=auth_openidc
  notify: reload apache

- name: setup keystone sso template
  template: src=etc/keystone/sso_callback_template.html
            dest=/etc/keystone/sso_callback_template.html
