---
- name: run insecure swift dispersion populate
  command: swift-dispersion-populate --insecure
  when: client.self_signed_cert|default('False')|bool
  run_once: True
  delegate_to: "{{ groups['swiftnode_primary'][0] }}"

- name: run swift dispersion populate
  command: swift-dispersion-populate
  when: not client.self_signed_cert|default('True')|bool
  run_once: True
  delegate_to: "{{ groups['swiftnode_primary'][0] }}"

