---
- name: install memcached packages
  apt: pkg={{ item }}
  with_items:
    - memcached
    - python-memcache
    - libsasl2-dev
  register: result
  until: result|succeeded
  retries: 5

- name: "remove /nonexistent inadvertently created by memcached package: see https://bugs.launchpad.net/ubuntu/+source/memcached/+bug/1255328/"
  file: dest=/nonexistent state=absent

- name: memcached configuration
  template: src=memcached.conf dest=/etc/memcached.conf mode=0644
  notify:
    - restart memcached

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool
