---
- name: fetch rados.py
  get_url: url={{ ceph.rados_url }}
           dest="/opt/openstack/current/nova/lib/python2.7/site-packages/rados.py"
           owner=root
           group=root
           mode=0644

- name: fetch rbd.py
  get_url: url={{ ceph.rbd_url }}
           dest="/opt/openstack/current/nova/lib/python2.7/site-packages/rbd.py"
           owner=root
           group=root
           mode=0644

- name: fetch nova keyring
  slurp: path=/etc/ceph/ceph.client.nova.keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: nova_keyring

- name: write nova keyring
  copy:
    dest: "{{ nova_keyring['source'] }}"
    content: "{{ nova_keyring['content'] | b64decode }}"
    mode: 0644
    #owner: cinder
    #group: cinder

# used in nova.conf
- name: fetch contents of uuid file
  slurp: path=/etc/ceph/nova_uuid
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: nova_uuid_file
