---
dependencies:
  - role: keystone-defaults
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: keystone
    logdata: "{{ keystone.logs }}"
  - role: openstack-source
    project_name: keystone
    project_rev: "{{ keystone.source.rev }}"
    alternatives: "{{ keystone.alternatives }}"
    system_dependencies: "{{ keystone.source.system_dependencies }}"
    python_dependencies: "{{ keystone.source.python_dependencies }}"
    constrain: "{{ keystone.source.constrain }}"
    upper_constraints: "{{ keystone.source.upper_constraints }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: keystone
    alternatives: "{{ keystone.alternatives }}"
    when: openstack_install_method == 'package'
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
  - role: openstack-database
    database_name: keystone
  - role: apache
