---
- name: comment out default memcached ip address
  lineinfile: dest=/etc/memcached.conf
              regexp='^-l 0.0.0.0'
              line="# -l 0.0.0.0" state=present

- name: use bond0 ip address for memcached
  lineinfile: dest=/etc/memcached.conf insertafter="^# -l"
              line="-l {{ hostvars[inventory_hostname][primary_interface]['ipv4']['address'] }}"
              state=present
  notify: restart memcached

- name: permit swift proxy from anywhere
  ufw: rule=allow to_port=8090 proto=tcp

- name: swift-proxy service script
  template: src=roles/swift-common/templates/etc/init/swift-service.conf
            dest=/etc/init/swift-{{ item.service_name }}.conf mode=0644
  with_items:
    - { service_name: proxy, conf: proxy-server }

- name: configure swift-proxy
  template: src=etc/swift/proxy-server.conf dest=/etc/swift/proxy-server.conf
            owner=swift group=swift mode=0640
  notify: restart swift-proxy service

- meta: flush_handlers

- name: start swift-proxy service
  service: name=swift-proxy state=started
