---
- name: permit swift proxy from anywhere
  ufw: rule=allow to_port=8090 proto=tcp
  tags: ufw

- name: swift-proxy service script
  upstart_service: name=swift-proxy
                   cmd=/usr/local/bin/swift-proxy-server
                   args=/etc/swift/proxy-server.conf
                   user=swift

- stat: path=/etc/swift/object.ring.gz
  register: object_ring

- stat: path=/etc/swift/container.ring.gz
  register: container_ring

- stat: path=/etc/swift/account.ring.gz
  register: account_ring

- set_fact: start_proxy={{ container_ring.stat.exists }} and 
                        {{ object_ring.stat.exists }} and
                        {{ account_ring.stat.exists }}

- name: configure swift-proxy
  template: src=etc/swift/proxy-server.conf dest=/etc/swift/proxy-server.conf
            owner=swift group=swift mode=0640
  notify:
    - restart swift-proxy service

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart swift-proxy service
  when: code_has_changed | default('False') | bool and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: start swift-proxy services
  service: name=swift-proxy state=started
  when: start_proxy|bool
